server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/signalops
    username: signalops
    password: signalops
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "signalops-dev-secret-please-change-this-to-64-chars-minimum-123456"
  expiration: 86400000

